apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-frontend        # thêm prefix dev
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-frontend
  template:
    metadata:
      labels:
        app: dev-frontend
    spec:
      imagePullSecrets:
        - name: ecr-regcred
      containers:
      - name: frontend
        image: 980921740481.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:4918eca
        ports:
        - containerPort: 80
        env:
        - name: APP_API_HOST
          value: "dev-backend-svc"  # trỏ tới backend dev
        - name: APP_API_PORT
          value: "80"
