apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-regcred
      containers:
      - name: frontend
        image: 980921740481.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:bb45d7b
        ports:
        - containerPort: 80
        env:
        - name: APP_API_HOST
          value: "backend"
        - name: APP_API_PORT
          value: "80"
