apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-frontend-ingress
  namespace: my-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: trongduong.website
    http:
      paths:
      - path: /dev
        pathType: Prefix
        backend:
          service:
            name: dev-frontend
            port:
              number: 80
