apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ecr-regcred
      containers:
      - name: backend
        image: 980921740481.dkr.ecr.ap-southeast-1.amazonaws.com/backend:d2f9382
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "postgres"
        envFrom:
        - secretRef:
            name: postgres-secret
