apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-backend-ingress
  namespace: my-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: trongduong.website
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: prod-backend
            port:
              number: 80